<?php

namespace ContainerBZn89Fo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZGVGqp5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zGVGqp5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zGVGqp5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'session' => ['privates', '.errored.ZU82lbO', NULL, 'Cannot determine controller argument for "App\\Controller\\StripeController::createCharge()": the $session argument is type-hinted with the non-existent class or interface: "App\\Controller\\SessionInterface". Did you forget to add a use statement?'],
        ], [
            'session' => '?',
        ]);
    }
}
