#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_send_email:
  path: /devis/{id}/send-email
  controller: App\Controller\DevisController::sendMail
#    controller: App\Controller\DefaultController::index 
#app_constat_filter:
    #path: /constat/constats/filter
    #methods: [POST]
    #controller: App\Controller\ConstatController::filter
app_sort_constat_by_date:
    path: /constat/sort-constat-by-date
    controller: App\Controller\ConstatController::sortByDate

