<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAnfxxPt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAnfxxPt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAnfxxPt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAnfxxPt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAnfxxPt\App_KernelDevDebugContainer([
    'container.build_hash' => 'AnfxxPt',
    'container.build_id' => '77e39dca',
    'container.build_time' => 1678284083,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAnfxxPt');
