<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLBhalnz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLBhalnz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLBhalnz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLBhalnz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLBhalnz\App_KernelDevDebugContainer([
    'container.build_hash' => 'LBhalnz',
    'container.build_id' => 'd2557ca1',
    'container.build_time' => 1678221107,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLBhalnz');
