<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0f8EZJz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0f8EZJz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0f8EZJz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0f8EZJz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0f8EZJz\App_KernelDevDebugContainer([
    'container.build_hash' => '0f8EZJz',
    'container.build_id' => '80d4d37c',
    'container.build_time' => 1678193718,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0f8EZJz');
